name: Release and Tag
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Initialize git
        run: |
          git config --global user.email "contact@styve-lioumba.fr"
          git config --global user.name "Styve Lioumba"
      - name: Create release tag
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: End message
        run: echo "End of release"

